### ISSUE TITLE
Try plugging in Adapter into the grey scott model

### ISSUE THREAD

**Issue by lukemartinlogan** [scs-lab/coeus-adapter#12]
Try augmenting the adios2.xml file for the GS model to use the Hermes Engine. 

The GS model is here: https://github.com/pnorbert/adiosvm/tree/master/Tutorial/gray-scott

**Comment by coreprinciple6** [comment]
<adios-config>
    <io name="writer">
        <engine type="Plugin">
            <parameter key="PluginName" value="/tmp/myFile.bp" />
            <parameter key="PluginLibrary" value="hermes_engine" />
            
        </engine>
    </io>
</adios-config>

**Comment by lukemartinlogan** [comment]
We were able to successfully plugin the Hermes engine into the grey-scott model.

```
git clone https://github.com/pnorbert/adiosvm.git
cd adiosvm/Tutorial/grey-scott
mkdir build
cd build
cmake ../ -DCMAKE_BUILD_TYPE=Release
make -j8
export LD_LIBRARY_PATH=/path/to/coeus/lib (the directory which contians libhermes_engine.so)
mpirun -n 4 build/gray-scott simulation/settings-files.json
```
