### ISSUE TITLE
Add print statements to the custom ADIOS driver + build unit test

### ISSUE THREAD

**Issue by lukemartinlogan** [scs-lab/coeus-adapter#3]
Create a unit test to ensure the custom driver can be loaded. Add print statements.

Example Engine: https://github.com/ornladios/ADIOS2/tree/master/plugins/engines

**Comment by JaimeCernuda** [comment]
Take a look at this engine
https://github.com/ornladios/ADIOS2/tree/master/source/adios2/engine/null
